version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 3200:3200
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/pastel-africa
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always